// Exportación .set/json/csv y portapapeles.

import { track } from './track.js';
import { buildSetFile, buildRefinementSetFile, buildReport, buildCsv, downloadText, formatSetValue } from './export.js';
import { t, L, localeTag } from './i18n.js';
import { state, api, $, esc, paramValue } from './ui-state.js';
import { verdictCopy, displayVerdictCopy, holdoutFact, whyGradeHighlights, nextStepText } from './ui-verdict.js';

const plain = (s) => String(s ?? '').replace(/<[^>]+>/g, '');

/**
 * Resumen en texto plano, pensado para el usuario que se abruma con las 7 pestañas y
 * antes copiaba todo a mano para pedirle a una IA externa que se lo explicara. Usa los
 * mismos datos que ya calcula Verdict (mismo veredicto, mismos pros/contras
 * destacados) en vez de generar nada nuevo: no llama a ningun modelo, así que es
 * instantaneo, gratis, y los datos de la estrategia no salen del navegador.
 */
export function buildPlainSummary(a) {
  const dv = displayVerdictCopy(a);
  const c = verdictCopy(dv.level);
  const top = a.plateaus.slice(0, 3);
  const hold = holdoutFact(a);
  const { pros, cons } = whyGradeHighlights(a);
  const hasF = a.meta.hasForward;
  const lines = [];

  lines.push(L('RESUMEN OROMETRA', 'OROMETRA SUMMARY'));
  lines.push('='.repeat(40));
  lines.push('');
  // El titular ya empieza casi siempre por el nivel («Evidencia buena: …»): no se repite.
  const headline = plain(dv.headline);
  lines.push(headline.toLowerCase().startsWith(String(c.label).toLowerCase()) ? headline : `${c.label}: ${headline}`);
  if (dv.summary) lines.push(plain(dv.summary));
  lines.push('');

  // Top 3, no solo "la mejor": cual conviene tambien depende de criterios operativos
  // (ej. frecuencia de operacion) que la app no puede decidir por el usuario. Mismos
  // datos que la tabla comparativa de "Top 3" en Verdict.
  if (top.length) {
    lines.push(top.length === 1
      ? L('CONFIGURACIÓN GANADORA', 'WINNING CONFIGURATION')
      : L(`TOP ${top.length}: CONFIGURACIONES GANADORAS`, `TOP ${top.length}: WINNING CONFIGURATIONS`));
    top.forEach((p, i) => {
      const role = i === 0 ? L('Recomendada', 'Recommended') : L(`Alternativa ${i}`, `Alternative ${i}`);
      lines.push('');
      lines.push(`${role} — ${L('Pasada', 'Pass')} ${p.record.id} (${L('meseta', 'plateau')} ${p.rank}, ${L('robustez', 'robustness')} ${p.robust.toFixed(0)}/100)`);
      lines.push(`  ${L('Operaciones periodo optimizado / forward', 'Optimized-period / forward trades')}: ${p.record.is.trades}${hasF ? ` / ${p.record.oos.trades}` : ` / ${L('sin forward', 'no forward')}`}`);
      a.meta.paramNames.forEach((n, j) => lines.push(`  ${n} = ${paramValue(p.record.params[j])}`));
    });
    lines.push('');
  }

  if (pros.length) {
    lines.push(L('A FAVOR', 'IN FAVOR'));
    pros.forEach((f) => lines.push(`- ${plain(f.title)}: ${plain(f.detail)}`));
    lines.push('');
  }
  if (cons.length) {
    lines.push(L('EN CONTRA / LÍMITES', 'AGAINST / LIMITS'));
    cons.forEach((f) => lines.push(`- ${plain(f.title)}: ${plain(f.detail)}`));
    lines.push('');
  }

  lines.push(L('PERIODO NO VISTO (HOLDOUT)', 'UNSEEN PERIOD (HOLDOUT)'));
  lines.push(`${plain(hold.value)}${hold.note ? ' — ' + plain(hold.note) : ''}`);
  lines.push('');

  lines.push(L('QUÉ HACER AHORA', 'WHAT TO DO NOW'));
  // El mismo siguiente paso que la pantalla: cambia cuando ya se ha probado el periodo no visto.
  lines.push(plain(nextStepText(a, hold)));
  lines.push('');

  lines.push('-'.repeat(40));
  lines.push(L(
    `Generado por Orometra el ${new Date().toLocaleString(localeTag())}. Este resumen recoge solo lo esencial; el informe completo (JSON/CSV) tiene todo el detalle.`,
    `Generated by Orometra on ${new Date().toLocaleString(localeTag())}. This summary keeps only the essentials; the full report (JSON/CSV) has every detail.`,
  ));
  return lines.join('\n');
}

export async function copyParams(index, button) {
  track('copiar-parametros');
  const a = state.analysis;
  if (!a || !a.plateaus.length) return;
  const p = a.plateaus[Math.min(index, a.plateaus.length - 1)];
  // Mismo formato que el .set de MT5 (punto decimal), no Intl local.
  const text = a.meta.paramNames
    .map((n, j) => `${n}=${formatSetValue(p.record.params[j])}`)
    .join('\n');
  const original = button.textContent;
  try {
    await navigator.clipboard.writeText(text);
    button.textContent = L('Copiado ✓', 'Copied ✓');
  } catch {
    button.textContent = L('No se ha podido copiar', 'Could not copy');
  }
  setTimeout(() => { button.textContent = original; }, 1800);
}

// ---------------------------------------------------------------- exportación
export function doExport(kind, plateauIndex) {
  const a = state.analysis;
  if (!a) return;
  track(`descarga-${kind}`);
  const stamp = new Date().toISOString().slice(0, 10);
  const idx = Number.isFinite(plateauIndex) ? plateauIndex : state.selectedPlateau;
  const best = a.plateaus[Math.min(idx, Math.max(0, a.plateaus.length - 1))];
  if (kind === 'set') {
    if (!best) return api.showError(L('No hay ninguna meseta que exportar.', 'There is no plateau to export.'));
    if (!a.meta.hasForward) {
      return api.showError(L(
        'Sin forward no se exporta un .set de despliegue: la meseta solo se midió en el periodo optimizado. Exporta el rango de refinamiento, o vuelve a auditar con el archivo forward.',
        'Without forward, a deployment .set is not exported: the plateau was only measured on the optimized period. Export the refinement range, or re-audit with the forward file.',
      ));
    }
    downloadText(`orometra-M${best.rank}-pass${best.record.id}.set`, buildSetFile(a, best, state.searchSet));
  } else if (kind === 'refine') {
    if (!best) return api.showError(L('No hay ninguna meseta que refinar.', 'There is no plateau to refine.'));
    downloadText(`orometra-M${best.rank}-${L('refinamiento', 'refinement')}.set`, buildRefinementSetFile(a, best, state.searchSet));
  } else if (kind === 'json') {
    downloadText(`orometra-${L('informe', 'report')}-${stamp}.json`, JSON.stringify(buildReport(a, {
      source: state.source ? { is: state.source.is, oos: state.source.oos || null, at: state.source.at } : null,
      shownVerdict: displayVerdictCopy(a),
    }), null, 2), 'application/json');
  } else if (kind === 'csv') {
    downloadText(`orometra-${L('configuraciones', 'configurations')}-${stamp}.csv`, buildCsv(a), 'text/csv;charset=utf-8');
  } else if (kind === 'summary') {
    downloadText(`orometra-${L('resumen', 'summary')}-${stamp}.txt`, buildPlainSummary(a));
  }
}

export let closeExportMenu = null;

export function toggleExportMenu() {
  if (closeExportMenu) {
    closeExportMenu();
    return;
  }
  let menu = $('#exportMenu');
  if (menu) menu.remove();
  menu = document.createElement('div');
  menu.id = 'exportMenu';
  menu.className = 'export-menu';
  menu.innerHTML = `
    <button data-export="summary">${esc(t('export.summary'))}</button>
    <button data-export="json">${esc(t('export.json'))}</button>
    <button data-export="csv">${esc(t('export.csv'))}</button>
    <button data-export="set" ${state.analysis && !state.analysis.meta.hasForward ? 'disabled title="' + esc(L('Requiere forward', 'Requires forward')) + '"' : ''}>${esc(t('export.set'))}</button>
    <button data-export="refine">${esc(t('export.refine'))}</button>`;
  $('.top-actions').appendChild(menu);
  menu.querySelectorAll('[data-export]').forEach((b) => b.addEventListener('click', () => {
    // El menú ofrece la configuración PROPUESTA (M1), no la última meseta que se miró en
    // la pestaña de mesetas: si no, tras abrir una alternativa se bajaba el .set de M2
    // con la etiqueta «propuesta». Las fichas de cada meseta tienen su propio botón.
    doExport(b.dataset.export, 0);
    menu.remove();
  }));
  // Un único punto de cierre: así no se acumula un listener por cada apertura.
  const onDocClick = (e) => {
    if (!menu.contains(e.target) && e.target !== $('#exportBtn')) closeExportMenu();
  };
  const onKey = (e) => {
    if (e.key === 'Escape') {
      closeExportMenu();
      $('#exportBtn').focus();
    }
  };
  closeExportMenu = () => {
    document.removeEventListener('click', onDocClick);
    document.removeEventListener('keydown', onKey);
    menu.remove();
    closeExportMenu = null;
  };
  setTimeout(() => {
    document.addEventListener('click', onDocClick);
    document.addEventListener('keydown', onKey);
  }, 0);
}
