// Exportación .set/json/csv y portapapeles.

import { buildSetFile, buildRefinementSetFile, buildReport, buildCsv, downloadText, formatSetValue } from './export.js';
import { t, L, localeTag } from './i18n.js';
import { state, api, $, esc, paramValue } from './ui-state.js';
import { verdictCopy, displayVerdictLevel, holdoutFact, whyGradeHighlights } from './ui-verdict.js';

const plain = (s) => String(s ?? '').replace(/<[^>]+>/g, '');

/**
 * Resumen en texto plano, pensado para el usuario que se abruma con las 7 pestañas y
 * antes copiaba todo a mano para pedirle a una IA externa que se lo explicara. Usa los
 * mismos datos que ya calcula Verdict (mismo veredicto, mismos pros/contras
 * destacados) en vez de generar nada nuevo: no llama a ningun modelo, así que es
 * instantaneo, gratis, y los datos de la estrategia no salen del navegador.
 */
export function buildPlainSummary(a) {
  const v = a.verdict;
  const displayLevel = displayVerdictLevel(a);
  const c = verdictCopy(displayLevel);
  const best = a.plateaus[0];
  const hold = holdoutFact(a);
  const { pros, cons } = whyGradeHighlights(a);
  const lines = [];

  lines.push(L('RESUMEN OROMETRA', 'OROMETRA SUMMARY'));
  lines.push('='.repeat(40));
  lines.push('');
  lines.push(`${c.label}: ${plain(v.headline)}`);
  if (v.summary) lines.push(plain(v.summary));
  lines.push('');

  if (best) {
    lines.push(L('CONFIGURACIÓN RECOMENDADA', 'RECOMMENDED CONFIGURATION'));
    lines.push(`Pass ${best.record.id} (M${best.rank}, ${L('robustez', 'robustness')} ${best.robust.toFixed(0)}/100)`);
    a.meta.paramNames.forEach((n, j) => lines.push(`  ${n} = ${paramValue(best.record.params[j])}`));
    lines.push('');
  }

  if (pros.length) {
    lines.push(L('A FAVOR', 'IN FAVOR'));
    pros.forEach((f) => lines.push(`- ${plain(f.title)}: ${plain(f.detail)}`));
    lines.push('');
  }
  if (cons.length) {
    lines.push(L('EN CONTRA / LÍMITES', 'AGAINST / LIMITS'));
    cons.forEach((f) => lines.push(`- ${plain(f.title)}: ${plain(f.detail)}`));
    lines.push('');
  }

  lines.push(L('PERIODO NO VISTO (HOLDOUT)', 'UNSEEN PERIOD (HOLDOUT)'));
  lines.push(`${plain(hold.value)}${hold.note ? ' — ' + plain(hold.note) : ''}`);
  lines.push('');

  lines.push(L('QUÉ HACER AHORA', 'WHAT TO DO NOW'));
  lines.push(plain(v.nextStep));
  lines.push('');

  lines.push('-'.repeat(40));
  lines.push(L(
    `Generado por Orometra el ${new Date().toLocaleString(localeTag())}. Este resumen recoge solo lo esencial; el informe completo (JSON/CSV) tiene todo el detalle.`,
    `Generated by Orometra on ${new Date().toLocaleString(localeTag())}. This summary keeps only the essentials; the full report (JSON/CSV) has every detail.`,
  ));
  return lines.join('\n');
}

export async function copyParams(index, button) {
  const a = state.analysis;
  if (!a || !a.plateaus.length) return;
  const p = a.plateaus[Math.min(index, a.plateaus.length - 1)];
  // Mismo formato que el .set de MT5 (punto decimal), no Intl local.
  const text = a.meta.paramNames
    .map((n, j) => `${n}=${formatSetValue(p.record.params[j])}`)
    .join('\n');
  const original = button.textContent;
  try {
    await navigator.clipboard.writeText(text);
    button.textContent = L('Copiado ✓', 'Copied ✓');
  } catch {
    button.textContent = L('No se ha podido copiar', 'Could not copy');
  }
  setTimeout(() => { button.textContent = original; }, 1800);
}

// ---------------------------------------------------------------- exportación
export function doExport(kind, plateauIndex) {
  const a = state.analysis;
  if (!a) return;
  const stamp = new Date().toISOString().slice(0, 10);
  const idx = Number.isFinite(plateauIndex) ? plateauIndex : state.selectedPlateau;
  const best = a.plateaus[Math.min(idx, Math.max(0, a.plateaus.length - 1))];
  if (kind === 'set') {
    if (!best) return api.showError(L('No hay ninguna meseta que exportar.', 'There is no plateau to export.'));
    if (!a.meta.hasForward) {
      return api.showError(L(
        'Sin forward no se exporta un .set de despliegue: la región solo se midió in-sample. Exporta el rango de refinamiento, o vuelve a auditar con el archivo forward.',
        'Without forward, a deployment .set is not exported: the region was only measured in-sample. Export the refinement range, or re-audit with the forward file.',
      ));
    }
    downloadText(`robustness-M${best.rank}-pass${best.record.id}.set`, buildSetFile(a, best));
  } else if (kind === 'refine') {
    if (!best) return api.showError(L('No hay ninguna meseta que refinar.', 'There is no plateau to refine.'));
    downloadText(`robustness-M${best.rank}-refinamiento.set`, buildRefinementSetFile(a, best));
  } else if (kind === 'json') {
    downloadText(`robustness-informe-${stamp}.json`, JSON.stringify(buildReport(a, {
      source: state.source ? { is: state.source.is, oos: state.source.oos || null, at: state.source.at } : null,
    }), null, 2), 'application/json');
  } else if (kind === 'csv') {
    downloadText(`robustness-configuraciones-${stamp}.csv`, buildCsv(a), 'text/csv;charset=utf-8');
  } else if (kind === 'summary') {
    downloadText(`robustness-resumen-${stamp}.txt`, buildPlainSummary(a));
  }
}

export let closeExportMenu = null;

export function toggleExportMenu() {
  if (closeExportMenu) {
    closeExportMenu();
    return;
  }
  let menu = $('#exportMenu');
  if (menu) menu.remove();
  menu = document.createElement('div');
  menu.id = 'exportMenu';
  menu.className = 'export-menu';
  menu.innerHTML = `
    <button data-export="summary">${esc(t('export.summary'))}</button>
    <button data-export="json">${esc(t('export.json'))}</button>
    <button data-export="csv">${esc(t('export.csv'))}</button>
    <button data-export="set" ${state.analysis && !state.analysis.meta.hasForward ? 'disabled title="' + esc(L('Requiere forward', 'Requires forward')) + '"' : ''}>${esc(t('export.set'))}</button>
    <button data-export="refine">${esc(t('export.refine'))}</button>`;
  $('.top-actions').appendChild(menu);
  menu.querySelectorAll('[data-export]').forEach((b) => b.addEventListener('click', () => {
    doExport(b.dataset.export);
    menu.remove();
  }));
  // Un único punto de cierre: así no se acumula un listener por cada apertura.
  const onDocClick = (e) => {
    if (!menu.contains(e.target) && e.target !== $('#exportBtn')) closeExportMenu();
  };
  const onKey = (e) => {
    if (e.key === 'Escape') {
      closeExportMenu();
      $('#exportBtn').focus();
    }
  };
  closeExportMenu = () => {
    document.removeEventListener('click', onDocClick);
    document.removeEventListener('keydown', onKey);
    menu.remove();
    closeExportMenu = null;
  };
  setTimeout(() => {
    document.addEventListener('click', onDocClick);
    document.addEventListener('keydown', onKey);
  }, 0);
}
