// Veredicto, evidencia, why-grade, outcome y top3.

import { qualityLabel } from '../core/metrics.js';
import { outcomeFromAnalysis, CODE, errorCopy } from '../core/errors.js';
import { scatterIsOos, degradationChart } from './charts.js';
import { t, L, localeTag } from './i18n.js';
import { state, num, int, pct, esc, rich, nf, paramValue } from './ui-state.js';

/*
 * El sello califica la FUERZA DE LA EVIDENCIA, no la estrategia. Antes decia
 * "NO RECOMENDADO" / "SUPERA LA AUDITORIA", que era decidir por el usuario sobre algo
 * que la aplicacion no mide. Ahora describe lo que sostiene el hallazgo.
 */
export function verdictCopy(level) {
  if (level === 'insufficient') return { label: t('verdict.insufficient'), cls: 'v-no' };
  if (level === 'weak') return { label: t('verdict.weak'), cls: 'v-weak' };
  if (level === 'moderate') return { label: t('verdict.moderate'), cls: 'v-warn' };
  return { label: t('verdict.strong'), cls: 'v-go' };
}

/** Estado del holdout para sello / hoja de evidencia (forward ≠ periodo no visto). */
export function holdoutFact(a) {
  const res = state.unseen && state.unseen.result;
  if (!res) {
    return {
      value: L('No aportado', 'Not supplied'),
      note: a && a.meta && a.meta.hasForward
        ? L('El forward ya entró en la selección. Falta un tramo no visto.', 'Forward already entered selection. An unseen segment is still missing.')
        : L('Validación independiente aún no cargada.', 'Independent validation not loaded yet.'),
      short: L('Holdout: no aportado', 'Holdout: not supplied'),
      done: false,
      ok: false,
    };
  }
  const value = res.level === 'normal'
    ? L('Normal', 'Normal')
    : res.level === 'tail'
      ? L('En la cola', 'In the tail')
      : L('Fuera de rango', 'Out of range');
  return {
    value,
    note: res.headline || '',
    short: L(`Holdout: ${value}`, `Holdout: ${value}`),
    done: true,
    ok: res.level === 'normal' || res.level === 'tail',
  };
}

/**
 * Evidencia "fuerte" sin holdout limpio se muestra como moderada: el forward ya se usó.
 */
export function displayVerdictLevel(a) {
  let level = a.verdict.level;
  if (level === 'strong' && a.meta.hasForward) {
    const h = holdoutFact(a);
    if (!h.done || !h.ok) level = 'moderate';
  }
  return level;
}

export function renderVerdict(a) {
  const v = a.verdict;
  const displayLevel = displayVerdictLevel(a);
  const c = verdictCopy(displayLevel);
  const best = a.plateaus[0];
  const mainRisk = (v.findings || []).find((f) => f.severity === 'critical' || f.severity === 'warn');
  const hold = holdoutFact(a);
  const demoNote = state.isDemo
    ? `<div class="demo-note">${L(
      `Estos datos son <strong>sintéticos</strong>, generados por la aplicacion para que puedas ver el flujo completo. La meseta real esta plantada en: ${esc(Object.entries(state.demoTruth.center).map(([k, val]) => `${k}=${val}`).join(', '))}.`,
      `These data are <strong>synthetic</strong>, generated by the app so you can see the full flow. The real plateau is planted at: ${esc(Object.entries(state.demoTruth.center).map(([k, val]) => `${k}=${val}`).join(', '))}.`,
    )}</div>`
    : '';

  const src = state.source;
  const stamp = src
    ? `<div class="run-stamp">
        <span class="run-files">${esc(src.is)}${src.oos ? ' <b>+</b> ' + esc(src.oos) : ''}</span>
        <span class="run-sep">·</span>
        <span>${int(a.meta.total)} ${L('configuraciones', 'configurations')}</span>
        <span class="run-sep">·</span>
        <span>${esc(L('analizado', 'analyzed'))} ${esc(src.at.toLocaleString(localeTag(), { dateStyle: 'short', timeStyle: 'short' }))}</span>
        <span class="run-sep">·</span>
        <span title="${esc(L('Mínimos exigidos en este análisis', 'Minima required in this analysis'))}">PF ≥ ${num(a.meta.policy.gates.minProfitFactor, 2)} · DD ≤ ${num(a.meta.policy.gates.maxDrawdownPct, 0)} % · ${int(a.meta.minTradesIs)} ops</span>
        <span class="run-sep">·</span>
        <span class="run-holdout" title="${esc(hold.note)}">${esc(hold.short)}</span>
      </div>`
    : '';

  const pickBlock = best
    ? `<div class="verdict-fact">
        <span class="verdict-fact-label">${esc(t('verdict.pick'))}</span>
        <strong class="verdict-fact-value mono">Pass ${esc(best.record.id)}</strong>
        <span class="verdict-fact-note">M${best.rank} · ${int(best.size)} ${L('configs', 'configs')} · ${num(best.robust, 0)} ${L('robustez', 'robustness')}</span>
      </div>`
    : `<div class="verdict-fact">
        <span class="verdict-fact-label">${esc(t('verdict.pick'))}</span>
        <strong class="verdict-fact-value">${esc(t('verdict.nopick'))}</strong>
      </div>`;

  const holdBlock = `<div class="verdict-fact${hold.done && !hold.ok ? ' verdict-fact-risk' : ''}">
      <span class="verdict-fact-label">${L('Holdout', 'Holdout')}</span>
      <strong class="verdict-fact-value">${esc(hold.value)}</strong>
      <span class="verdict-fact-note">${esc(hold.note)}</span>
      ${!hold.done ? `<button class="text-btn verdict-fact-cta" data-goto="unseen">${L('Ir al periodo no visto &rarr;', 'Go to unseen period &rarr;')}</button>` : ''}
    </div>`;

  const riskBlock = mainRisk
    ? `<div class="verdict-fact verdict-fact-risk">
        <span class="verdict-fact-label">${esc(t('verdict.risk'))}</span>
        <strong class="verdict-fact-value">${esc(mainRisk.title)}</strong>
        <span class="verdict-fact-note">${esc(mainRisk.detail)}</span>
      </div>`
    : '';

  // "Why this evidence grade" ya abre con los primeros 4 pros y 4 contras; el resto de
  // hallazgos (o todos, si no hubo highlights) va en "More engine findings" mas abajo,
  // sin repetir el mismo texto dos veces en la misma pestana.
  const highlights = whyGradeHighlights(a);
  const shown = new Set([...highlights.pros, ...highlights.cons]);
  const restFindings = v.findings.filter((f) => !shown.has(f));

  return `${demoNote}${stamp}
  ${renderOutcomeBanner(a)}
  <section class="verdict-banner ${c.cls}">
    <div class="verdict-stamp-col">
      <div class="verdict-stamp">${c.label}</div>
    </div>
    <div class="verdict-body">
      <h2>${esc(v.headline)}</h2>
      ${v.summary ? `<p>${esc(v.summary)}</p>` : ''}
    </div>
    <div class="verdict-aside">
      ${pickBlock}
      ${holdBlock}
      ${riskBlock}
      <div class="verdict-fact verdict-fact-next">
        <span class="verdict-fact-label">${esc(t('verdict.next'))}</span>
        <strong class="verdict-fact-value">${esc(v.nextStep)}</strong>
      </div>
    </div>
  </section>

  ${renderEvidenceSheet(a, best)}

  ${renderWhyGrade(a, highlights)}

  ${best ? renderStableRanges(a, best) : ''}

  ${renderTop3(a)}

  ${restFindings.length ? `<section class="panel panel-evidence">
    <div class="panel-head"><div><div class="panel-kicker">${L('Detalle', 'Detail')}</div><h2>${L('Más hallazgos del motor', 'More engine findings')}</h2></div></div>
    <ul class="findings">
      ${restFindings.map((f) => `<li class="finding f-${f.severity === 'critical' ? 'block' : f.severity}">
        <div class="finding-mark" aria-hidden="true"></div>
        <div><strong>${esc(f.title)}</strong><p>${rich(f.detail)}</p></div>
      </li>`).join('')}
    </ul>
  </section>` : ''}

  <div class="grid-secondary">
    <section class="panel">
      <div class="panel-head compact"><div><div class="panel-kicker">${L('Transferencia', 'Transfer')}</div><h2>${L('Calidad in-sample frente a forward', 'In-sample quality vs forward')}</h2></div></div>
      ${scatterIsOos(a)}
      <p class="chart-note">${L(
        'Cada punto es una configuracion. La diagonal marca &laquo;no se degrada&raquo;. Los puntos por debajo pierden calidad fuera de muestra. En verde, las que forman meseta.',
        'Each point is a configuration. The diagonal marks &laquo;no degradation&raquo;. Points below lose quality out of sample. In green, those that form a plateau.',
      )}</p>
    </section>
    <section class="panel">
      <div class="panel-head compact"><div><div class="panel-kicker">${L('Degradacion', 'Degradation')}</div><h2>${L('Que le pasa a tus mejores', 'What happens to your best')}</h2></div></div>
      ${degradationChart(a)}
      <p class="chart-note">${L(
        'Si D10 (tus mejores in-sample) no destaca sobre el resto, el ranking que usas para elegir no tiene valor predictivo.',
        'If D10 (your best in-sample) does not stand out from the rest, the ranking you use to choose has no predictive value.',
      )}</p>
    </section>
  </div>`;
}

export function samplingLabel(sampling) {
  return {
    grid: L('rejilla completa', 'full grid'),
    partial: L('cobertura parcial', 'partial coverage'),
    sparse: L('muestreo disperso / genético', 'sparse / genetic sampling'),
  }[sampling] || sampling;
}

export function renderOutcomeBanner(a) {
  const outcome = outcomeFromAnalysis(a);
  if (outcome.code === CODE.ANALYSIS_SUCCESS) return '';
  const copy = errorCopy(outcome.code, L);
  const cls = {
    [CODE.NO_QUALIFYING_CONFIGS]: 'outcome-no-qualifying',
    [CODE.INSUFFICIENT_DATA]: 'outcome-insufficient',
    [CODE.NO_PLATEAU]: 'outcome-no-plateau',
  }[outcome.code] || 'outcome-other';
  return `<section class="outcome-banner ${cls}" role="status">
    <strong>${esc(copy.title)}</strong>
    <p>${esc(copy.hint)}</p>
  </section>`;
}

export function renderEvidenceSheet(a, best) {
  const hasF = a.meta.hasForward;
  const cov = a.meta.coverage;
  const sc = a.meta.searchCoverage;
  let covTxt = Number.isFinite(cov)
    ? `${nf(cov >= 0.1 ? 1 : 4).format(cov * 100)} % · ${samplingLabel(a.meta.sampling)}`
    : '—';
  if (sc && sc.usable && Number.isFinite(sc.coverageSearch)) {
    covTxt += L(
      ` · .set ${nf(sc.coverageSearch >= 0.1 ? 1 : 2).format(sc.coverageSearch * 100)} %`,
      ` · .set ${nf(sc.coverageSearch >= 0.1 ? 1 : 2).format(sc.coverageSearch * 100)} %`,
    );
  } else if (!sc || !sc.present) {
    covTxt += L(' · sin .set', ' · no .set');
  }

  const covNote = sc && sc.usable && Number.isFinite(sc.coverageSearch)
    ? L(
      'Primero: fracción de la malla de niveles vistos en el archivo. Segundo (.set): fracción del espacio que pediste en MT5. Un genético puede subir el primero y dejar el segundo muy bajo.',
      'First: fraction of the seen-level grid in the file. Second (.set): fraction of the space you asked MT5 for. A genetic can inflate the first while leaving the second very low.',
    )
    : L(
      'Fracción del espacio de niveles vistos en tus archivos — no del rango del .set. Suelta el .set de la optimización para contrastarlo.',
      'Fraction of the seen-level space in your files — not the .set range. Drop the optimization .set to contrast it.',
    );
  const nb = best && best.neighborhood;
  let neighborsVal = '—';
  let neighborsNote = L('Sin meseta seleccionada', 'No plateau selected');
  if (nb) {
    neighborsVal = `${int(nb.passing)} / ${int(nb.observed)}`;
    const bits = [
      L(`${int(nb.passing)} pasan mínimos`, `${int(nb.passing)} pass minima`),
      L(`${int(nb.failing)} fallan`, `${int(nb.failing)} fail`),
    ];
    if (nb.slotsComplete && Number.isFinite(nb.gaps)) {
      bits.push(L(`${int(nb.gaps)} huecos no observados (de ${int(nb.slots)})`, `${int(nb.gaps)} unobserved gaps (of ${int(nb.slots)})`));
    } else {
      bits.push(L('huecos no estimables en este muestreo', 'gaps not estimable for this sampling'));
    }
    neighborsNote = bits.join(' · ');
  }

  const retentionVal = best && Number.isFinite(best.medianRetention)
    ? pct(best.medianRetention, 0)
    : (best && hasF && Number.isFinite(best.record.retention) ? pct(best.record.retention, 0) : '—');
  const retentionNote = hasF
    ? L('Retención de calidad en el forward (participó en la selección)', 'Quality retention on forward (took part in selection)')
    : L('Sin archivo forward', 'No forward file');

  const boundaryVal = best
    ? (best.boundary.length
      ? L(`Sí · ${best.boundary.map((b) => b.name).join(', ')}`, `Yes · ${best.boundary.map((b) => b.name).join(', ')}`)
      : L('No', 'No'))
    : '—';
  const boundaryNote = L(
    'Si toca el borde, la meseta podría continuar fuera del rango que optimizaste.',
    'If it touches the edge, the plateau may continue outside the range you optimized.',
  );

  const hold = holdoutFact(a);
  const holdoutVal = hold.value;
  const holdoutNote = hold.note;

  const plateauVal = best
    ? L(`Encontrada · M${best.rank} · ${int(best.size)} configs`, `Found · M${best.rank} · ${int(best.size)} configs`)
    : L('No encontrada', 'Not found');

  const rows = [
    [L('Meseta', 'Plateau'), plateauVal, L('Región conexa con soporte local, no un pico aislado.', 'Connected region with local support, not an isolated peak.')],
    [L('Cobertura de la optimización', 'Optimization coverage'), covTxt, covNote],
    [L('Vecinos (pasan / observados)', 'Neighbors (pass / observed)'), neighborsVal, neighborsNote],
    [L('Retención forward', 'Forward retention'), retentionVal, retentionNote],
    [L('Toca borde del rango', 'Touches search boundary'), boundaryVal, boundaryNote],
    [L('Holdout independiente', 'Independent holdout'), holdoutVal, holdoutNote],
  ];

  return `<section class="panel panel-evidence-sheet" aria-label="${esc(L('Hoja de evidencia', 'Evidence sheet'))}">
    <div class="panel-head compact">
      <div>
        <div class="panel-kicker">${L('Evidencia', 'Evidence')}</div>
        <h2>${L('Qué demuestran estos datos', 'What these data demonstrate')}</h2>
      </div>
    </div>
    <div class="evidence-sheet">
      ${rows.map(([label, value, note]) => `<div class="evidence-sheet-row" title="${esc(note)}">
        <span>${esc(label)}</span>
        <strong>${esc(value)}</strong>
        <em>${esc(note)}</em>
      </div>`).join('')}
    </div>
    <p class="chart-note">${L(
      'Forward forma parte de la selección. Un holdout no visto es la comprobación limpia. Una meseta es estabilidad en tu muestra — no una promesa de beneficio futuro.',
      'Forward takes part in selection. An unseen holdout is the clean check. A plateau is stability in your sample — not a promise of future profit.',
    )}</p>
  </section>`;
}

/** Primeros 4 pros y 4 contras: lo que abre "Why this evidence grade". Se calcula
 * aparte para poder excluirlos de "Engine findings" y no repetir el mismo texto dos
 * veces en la misma pestana. */
export function whyGradeHighlights(a) {
  const findings = a.verdict.findings || [];
  const pros = findings.filter((f) => f.severity === 'ok' || f.severity === 'info').slice(0, 4);
  const cons = findings.filter((f) => f.severity === 'warn' || f.severity === 'critical').slice(0, 4);
  return { pros, cons };
}

export function renderWhyGrade(a, highlights) {
  const { pros, cons } = highlights;
  if (!pros.length && !cons.length) return '';
  const col = (title, items, cls) => `<div class="why-col ${cls}">
    <h3>${esc(title)}</h3>
    <ul>${items.length
      ? items.map((f) => `<li><strong>${esc(f.title)}</strong><span>${esc(f.detail)}</span></li>`).join('')
      : `<li class="why-empty">${L('Nada destacado', 'Nothing notable')}</li>`}
    </ul>
  </div>`;
  return `<section class="panel panel-why">
    <div class="panel-head compact">
      <div>
        <div class="panel-kicker">${L('Lectura', 'Reading')}</div>
        <h2>${L('Por qué este grado de evidencia', 'Why this evidence grade')}</h2>
      </div>
    </div>
    <div class="why-grid">
      ${col(L('A favor', 'In favor'), pros, 'why-pros')}
      ${col(L('En contra / límites', 'Against / limits'), cons, 'why-cons')}
    </div>
  </section>`;
}

export function renderStableRanges(a, best) {
  const sens = a.sensitivity || [];
  const sensByName = new Map(sens.map((s) => [s.name, s]));
  const rows = (best.refinement || []).filter((r) => !r.constant && !r.fixed && !r.categorical && r.levels > 1);
  if (!rows.length) return '';
  const sensLabel = (name) => {
    const s = sensByName.get(name);
    const v = s && Number.isFinite(s.effective) ? s.effective : (s && s.sensitivity);
    if (!Number.isFinite(v)) return '—';
    if (v < 0.2) return L('Baja', 'Low');
    if (v < 0.45) return L('Media', 'Medium');
    return L('Alta', 'High');
  };
  return `<section class="panel panel-ranges">
    <div class="panel-head compact">
      <div>
        <div class="panel-kicker">${L('Rangos estables', 'Stable ranges')}</div>
        <h2>${L('Cuánto puedes mover cada parámetro', 'How far you can move each parameter')}</h2>
      </div>
      <button class="ghost-btn" data-export="refine" data-plateau-index="${best.rank - 1}">${L('.set de refinamiento', 'Refinement .set')}</button>
    </div>
    <p class="chart-note">${L(
      'Centro recomendado = Pass seleccionado. La zona es el rango de refinamiento alrededor de la meseta — no un intervalo de confianza.',
      'Recommended center = selected Pass. The zone is the refinement range around the plateau — not a confidence interval.',
    )}</p>
    <div class="range-table-wrap">
      <table class="range-table">
        <thead>
          <tr>
            <th>${L('Parámetro', 'Parameter')}</th>
            <th>${L('Centro', 'Center')}</th>
            <th>${L('Zona estable', 'Stable zone')}</th>
            <th>${L('Sensibilidad', 'Sensitivity')}</th>
          </tr>
        </thead>
        <tbody>
          ${rows.map((r) => `<tr>
            <td>${esc(r.name)}</td>
            <td class="mono">${paramValue(r.center)}</td>
            <td class="mono">${paramValue(r.start)} – ${paramValue(r.stop)}</td>
            <td>${sensLabel(r.name)}</td>
          </tr>`).join('')}
        </tbody>
      </table>
    </div>
  </section>`;
}

/**
 * Las tres mejores configuraciones, una al lado de otra y con TODOS sus parametros.
 *
 * Se comparan en columnas a propósito: cuando tres mesetas independientes coinciden
 * en el valor de un parámetro, ese valor es una conclusión solida del analisis. Y
 * donde discrepan, es que ese parámetro no decide el resultado, así que puedes
 * elegirlo por criterios operativos y dejar de afinarlo.
 */
export function renderTop3(a) {
  const top = a.plateaus.slice(0, 3);
  if (!top.length) {
    return `<section class="panel">
      <div class="panel-head compact"><div><div class="panel-kicker">${L('Decisión', 'Decision')}</div><h2>${L('Configuraciones ganadoras', 'Winning configurations')}</h2></div></div>
      <p class="muted">${L(
        'No hay ninguna región que cumpla los mínimos con estabilidad suficiente, así que no se propone ninguna configuracion. Revisa el',
        'No region meets the minima with enough stability, so no configuration is proposed. Check the',
      )} <button class="text-btn" data-goto="diagnostics">${L('diagnostico', 'diagnostics')}</button> ${L('para ver por que.', 'to see why.')}</p>
    </section>`;
  }
  const names = a.meta.paramNames;
  const agree = names.map((_, j) => {
    const vals = top.map((p) => p.record.params[j]);
    return vals.every((v) => v === vals[0]);
  });
  const agreeCount = agree.filter(Boolean).length;
  const WORD = {
    1: L('una', 'one'),
    2: L('dos', 'two'),
    3: L('tres', 'three'),
  };
  const word = WORD[top.length] || String(top.length);
  const showConsensus = top.length >= 2;
  const hasF = a.meta.hasForward;
  const featured = top[0];
  const alts = top.slice(1);

  const flagBadges = (p) => {
    const flags = [];
    if (p.invertedRisk && p.invertedRisk.length) {
      flags.push(`<span class="badge warn" title="${esc(L('Se apoya en un valor que el forward castiga', 'It relies on a value the forward punishes'))}">${L('valor castigado', 'punished value')}</span>`);
    }
    if (p.boundary.length) {
      flags.push(`<span class="badge warn" title="${esc(L('Pegada al borde del rango probado', 'Stuck to the edge of the tested range'))}">${L('borde', 'edge')}</span>`);
    }
    return flags.join(' ') || `<span class="badge ok">${L('sin avisos', 'no warnings')}</span>`;
  };

  const featuredCard = `<article class="t3-featured">
    <div class="t3-featured-head">
      <div>
        <div class="t3-rank">${L('Recomendada', 'Recommended')}</div>
        <div class="t3-pass">Pass ${esc(featured.record.id)}</div>
        <div class="t3-flags">${flagBadges(featured)}</div>
      </div>
      <div class="t3-score">${num(featured.robust, 0)}<small>${L('robustez', 'robustness')}</small></div>
    </div>
    <div class="t3-featured-metrics">
      <div><span>${L('Meseta', 'Plateau')}</span><strong>M${featured.rank} · ${int(featured.size)}</strong></div>
      <div><span>${L('Pasan / observadas', 'Pass / observed')}</span><strong>${featured.neighborhood
        ? `${int(featured.neighborhood.passing)} / ${int(featured.neighborhood.observed)}`
        : `${int(featured.stability.support)}`}</strong></div>
      <div><span>${L('Calidad IS', 'IS quality')}</span><strong>${num(featured.record.qualityIs, 2)}</strong></div>
      ${hasF ? `<div><span>${L('Calidad FW', 'FW quality')}</span><strong>${num(featured.record.qualityOos, 2)}</strong></div>` : ''}
    </div>
    <div class="t3-param-chips">
      ${names.map((n, j) => `<span class="${agree[j] && showConsensus ? 't3-chip-agree' : ''}">${esc(n)} <b>${paramValue(featured.record.params[j])}</b></span>`).join('')}
    </div>
    <div class="t3-featured-actions">
      <button class="primary-btn t3-btn-inline" data-export="set" data-plateau-index="${featured.rank - 1}">${L('Descargar .set', 'Download .set')}</button>
      <button class="ghost-btn t3-btn-inline" data-copy="${featured.rank - 1}">${L('Copiar parámetros', 'Copy parameters')}</button>
      <button class="text-btn t3-btn-inline" data-plateau="${featured.rank - 1}">${L('Ver detalle →', 'View detail →')}</button>
    </div>
  </article>`;

  const altCards = alts.length
    ? `<div class="t3-alts">
        ${alts.map((p, i) => `<article class="t3-alt">
          <div class="t3-rank">${L(`Alternativa ${i + 1}`, `Alternative ${i + 1}`)}</div>
          <div class="t3-pass">Pass ${esc(p.record.id)}</div>
          <div class="t3-score t3-score-sm">${num(p.robust, 0)}<small>${L('robustez', 'robustness')}</small></div>
          <div class="t3-flags">${flagBadges(p)}</div>
          <p class="t3-alt-meta">M${p.rank} · ${int(p.size)} ${L('configs', 'configs')} · ${int(p.stability.support)} ${L('vecinos', 'neighbors')}</p>
          <div class="t3-alt-actions">
            <button class="ghost-btn t3-btn-inline" data-export="set" data-plateau-index="${p.rank - 1}">.set</button>
            <button class="text-btn t3-btn-inline" data-plateau="${p.rank - 1}">${L('Detalle →', 'Detail →')}</button>
          </div>
        </article>`).join('')}
      </div>`
    : '';

  const header = top.map((p, i) => `<th class="t3-col ${i === 0 ? 't3-best' : ''}">
      <div class="t3-rank">${i === 0 ? L('Recomendada', 'Recommended') : L(`Alternativa ${i}`, `Alternative ${i}`)}</div>
      <div class="t3-pass">Pass ${esc(p.record.id)}</div>
    </th>`).join('');

  const metricRow = (label, fn, cls = '') => `<tr class="${cls}">
    <th class="t3-label">${esc(label)}</th>
    ${top.map((p, i) => `<td class="t3-col ${i === 0 ? 't3-best' : ''}">${fn(p)}</td>`).join('')}
  </tr>`;

  const paramRows = names.map((n, j) => `<tr class="${agree[j] ? 't3-agree' : ''}">
    <th class="t3-label mono">${esc(n)}${agree[j] ? `<span class="t3-tick" title="${esc(L(`Coinciden las ${word}`, `The ${word} agree`))}">✓</span>` : ''}</th>
    ${top.map((p, i) => `<td class="t3-col t3-value ${i === 0 ? 't3-best' : ''}">${paramValue(p.record.params[j])}</td>`).join('')}
  </tr>`).join('');

  return `<section class="panel t3-panel panel-recommend">
    <div class="panel-head">
      <div>
        <div class="panel-kicker">${L('Decisión', 'Decision')}</div>
        <h2>${top.length === 1
          ? L('Configuración ganadora', 'Winning configuration')
          : L(`Top ${top.length}: configuraciones ganadoras`, `Top ${top.length}: winning configurations`)}</h2>
      </div>
      ${showConsensus ? `<div class="t3-consensus">
        <strong>${L(`${agreeCount} de ${names.length}`, `${agreeCount} of ${names.length}`)}</strong>
        <span>${L(`parámetros en los que coinciden las ${word}`, `parameters where the ${word} agree`)}</span>
      </div>` : ''}
    </div>
    <p class="panel-intro">
      ${top.length === 1
        ? L(
          `Es la única región estable que ha superado los mínimos con soporte suficiente. Se elige por
           criterio maximin: es la configuración cuyo <em>peor</em> vecino es el mejor posible, no la que
           más rinde. Al haber una sola meseta no hay consenso entre regiones que contrastar.`,
          `It is the only stable region that cleared the minima with enough support. It is chosen by
           maximin: the configuration whose <em>worst</em> neighbor is the best possible, not the one
           that performs most. With a single plateau there is no cross-region consensus to contrast.`,
        )
        : L(
          `La recomendada es la meseta más sólida por criterio maximin. Las alternativas son otras
           regiones estables independientes: útiles si la recomendada choca con un criterio operativo.
           Las filas con <span class="t3-tick">✓</span> son el consenso más sólido del análisis.`,
          `The recommended pick is the strongest plateau by maximin. Alternatives are other
           independent stable regions — useful if the recommended one conflicts with an operational constraint.
           Rows with <span class="t3-tick">✓</span> are the most solid consensus in the analysis.`,
        )}
    </p>
    <div class="t3-podium">
      ${featuredCard}
      ${altCards}
    </div>
    ${showConsensus || top.length > 1 ? `<div class="table-wrap t3-compare-wrap">
      <table class="t3-table">
        <thead><tr><th class="t3-label">${L('Comparación', 'Comparison')}</th>${header}</tr></thead>
        <tbody>
          ${metricRow(L('Meseta', 'Plateau'), (p) => `M${p.rank} · ${int(p.size)} ${L('configs', 'configs')}${p.coreSize ? ` (${L('nucleo', 'core')} ${int(p.coreSize)})` : ''}`)}
          ${metricRow(L('Calidad in-sample', 'In-sample quality'), (p) => `${num(p.record.qualityIs, 2)} <em class="t3-tag">${esc(qualityLabel(p.record.qualityIs))}</em>`)}
          ${hasF ? metricRow(L('Calidad forward', 'Forward quality'), (p) => `${num(p.record.qualityOos, 2)} <em class="t3-tag">${esc(qualityLabel(p.record.qualityOos))}</em>`) : ''}
          ${hasF ? metricRow(L('Forward · PF / DD / ops', 'Forward · PF / DD / trades'), (p) => `${num(p.record.oos.profitFactor, 3)} / ${num(p.record.oos.drawdown, 1)}% / ${int(p.record.oos.trades)}`) : ''}
          ${metricRow(L('In-sample · PF / DD / ops', 'In-sample · PF / DD / trades'), (p) => `${num(p.record.is.profitFactor, 3)} / ${num(p.record.is.drawdown, 1)}% / ${int(p.record.is.trades)}`)}
          ${metricRow(L('Vecinos / suelo Q25', 'Neighbors / Q25 floor'), (p) => `${int(p.stability.support)} / ${num(p.stability.q25, 2)}`, 't3-sep')}
          <tr class="t3-params-head"><th class="t3-label" colspan="${top.length + 1}">${L('Parámetros de entrada', 'Input parameters')}</th></tr>
          ${paramRows}
        </tbody>
      </table>
    </div>` : ''}
  </section>`;
}
